name: Keyboard firmware build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build
      run: sed 's/ \-it//g' ./util/docker_build.sh > actions.sh | chmod +x actions.sh | /actions.sh planck/ez:kryptn
